---
- name: Run bundler
  bundler: state=present chdir=/vagrant/{{ name }}
- name: Run rake db:setup
  shell: bundle exec rake db:setup && touch /home/vagrant/{{ name }}_db_setup_finished
  args:
    chdir: /vagrant/{{ name }}
    creates: /home/vagrant/{{ name }}_db_setup_finished
- name: Run rake db:migrate
  shell: bundle exec rake db:migrate
  args:
    chdir: /vagrant/{{ name }}
