---
- name: Set {{ name }} site configuration
  become: yes
  template: src={{ template }} dest=/etc/nginx/sites-available/{{ name }} mode=0644
  vars:
    sitename: "{{ name }}"
  notify:
  - reload nginx
- name: Enable {{ name }} site
  become: yes
  file: src=/etc/nginx/sites-available/{{ name }} dest=/etc/nginx/sites-enabled/{{ name }} state=link
  notify:
  - reload nginx
