---
- name: Install required packages
  apt: name={{ item }}
  with_items:
    - software-properties-common
    - libffi-dev
    - libcurl4-gnutls-dev
    - git
    - build-essential
    - nodejs
    - apt-transport-https
    - ca-certificates
    - imagemagick
    - libmagickwand-dev
    - redis-server
