---
- name: Set hostname config
  become: yes
  copy:
    dest: /etc/hostname
    content: "{{ hostname }}"
  notify:
  - set hostname
- name: Set loopback host
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ hostname }}"
